breakfast_drink = "Juice/Milk/Coffee"
breakfast = [("Biscuits & Gravy", "Hashbrowns, Fruit", breakfast_drink),
             ("Omelettes, Bacon", "Applesauce", breakfast_drink),
             ("Cereal Hot/Cold", "Fruit, Toast", breakfast_drink),
             ("Cream Cheese/Bagels", "Ham, Fruit, Muffin", breakfast_drink),
             ("Oatmeal", "Fruit, Cinn. Roll", breakfast_drink),
             ("Grits", "Fruit, Muffin", breakfast_drink),
             ("Cream of Wheat", "Toast, Fruit", breakfast_drink),
             ("Egg/Sausage Sandwich", "Hashbrowns, Fruit", breakfast_drink),
             ("Buttermilk Pankcakes and Sausage", "Yogurt, Toast, Fruit", breakfast_drink),
             ("Waffles", "Ham, Hashbrowns, Fruit", breakfast_drink),
             ("Fruit Salad", "Yogurt, Granola", breakfast_drink),
             ("Veggie Omelette", "Whole Wheat Toast, Fruit", breakfast_drink),
             ("Whole Grain Cereal", "Banana Slices, Almond Milk", breakfast_drink),
             ("Quinoa Breakfast Bowl", "Sliced Strawberries, Almonds", breakfast_drink),
             ("Avocado Toast", "Poached Egg, Fresh Fruit", breakfast_drink),
             ("Scrambled Eggs with Spinach", "Whole Wheat English Muffin, Apple Slices", breakfast_drink),
             ("Breakfast Burrito", "Black Beans, Salsa, Fresh Fruit", breakfast_drink),
             ("Whole Wheat Pancakes", "Blueberry Compote, Greek Yogurt", breakfast_drink),
             ("Oatmeal with Nuts and Seeds", "Fresh Orange Juice", breakfast_drink),
             ("Egg White Frittata", "Spinach, Mushrooms, Whole Wheat Toast", breakfast_drink),
             ("Peanut Butter & Banana Toast", "Chia Seeds, Honey, Fruit Salad", breakfast_drink),
             ("Sweet Potato Hash", "Sautéed Spinach, Poached Egg", breakfast_drink),
             ("Egg White Frittata", "Spinach, Mushrooms, Whole Wheat Toast", breakfast_drink),
             ("Chorizo w/ Eggs", "Fruit, Toast", breakfast_drink)]

lunch = [("Chicken Quesadillas", "Bean Salad", "Pie"),
         ("Chicken Egg Rolls", "Fried Rice", "Tapioca Pudding"),
         ("Subway Sandwiches", "Chips", "Fruit Salad"),
         ("Chicken Caesar Salad", "Mac N Cheese", "Cookies"),
         ("Fetuccini Alfredo Chicken", "Salad, Carrots", "Cookies"),
         ("Beef Stragonoff", "Green Beans, Coleslaw", "Cake"),
         ("Coconut Shrimp", "Sweet Pot., Asparagus", "Strawberry Shortcake"),
         ("Chicken Nuggets", "Cucumber salad", "Potato Salad", "Brownies"),
         ("Beef/Cheese Raviolis", "Caesar Salad", "Garlic Bread", "Banana Pudding"),
         ("Baked Potato Soup", "Turkey Sandwich", "Fruit Salad"),
         ("Fish Tacos", "Coleslaw", "Zucchini and Cheese Casserole", "Pie"),
         ("BBQ Shredded Pork", "Potato Salad", "Veggies", "Brownies"),
         ("Shepherd's beef pie", "Salad, Biscuit, Brownies"),
         ("Tomato Soup", "Ham and Cheese Sandwiches", "Root-Beer Floats"),
         ("Clam Chowder", "Ham Sandwich", "Bread Pudding"),
         ("Tuna and Potato Patties", "Boiled Cabbage and Carrots", "Cupcakes"),
         ("Chicken Caesar Salad", "Mac N Cheese", "Cookies"),
         ("Tomato Soup", "Ham and Cheese Sandwiches", "Root-Beer Floats"),
         ("Baked Potato Soup", "Turkey Sandwich", "Fruit Salad"),
         ("Shrimp Po' Boy Sandwich", "Cajun Fries", "Pralines"),
         ("Mexican Street Corn Salad", "Chicken Enchiladas", "Churros"),
         ("Caprese Stuffed Portobello Mushrooms", "Garlic Bread", "Tiramisu"),
         ("Mediterranean Wrap", "Tabbouleh Salad", "Date Balls"),
         ("Meatloaf", "Macaroni and Cheese", "Carrots", "Peach Cobbler"),
         ("Tuna melt Sandwich", "Coleslaw", "Fruit Salad"),
         ("Sausage Pasta", "Garlic Bread, Peas", "Tapioca Pudding"),
         ("Chicken Pot Pie", "Carrot Souffle", "Fruit Ambrosia")]

dinner = [("Tuna Salad", "Corn, Salad", "Fruit"),
          ("Chicken Quesadillas", "Bean Salad", "Pie"),
          ("Chicken Egg Rolls", "Fried Rice", "Tapioca Pudding"),
          ("Subway Sandwiches", "Chips", "Fruit Salad"),
          ("Corn Dogs", "Coleslaw", "Ice-Cream"),
          ("Chicken Salad", "French Fries", "Pudding"),
          ("Clam Chowder", "Ham Sandwiches", "Pie"),
          ("Chili", "Grilled Cheese Sandwich", "Fruit Salad"),
          ("Tuna Patties", "Creamed Corn", "Cupcake"),
          ("Soft Beef Tacos", "Cilantro Rice", "Ice-Cream"),
          ("Albondigas Soup", "Quesadilla", "Pie"),
          ("Boneless Wings", "Potatoes", "Fruit Salad"),
          ("Honey Baked Chicken", "Mashed Potatoes, Veggies", "Cake"),
          ("Chicken Teriyaki", "Veggies, Rice", "Berry Shortcake"),
          ("Spaghetti and Meat Sauce", "Garlic Bread", "Caesar Salad", "Ice-Cream"),
          ("Grilled Lemon Herb Salmon", "Quinoa Salad", "Fruit Kabobs"),
          ("Vegetable Stir-Fry", "Steamed Brown Rice", "Mango Sorbet"),
          ("Lemon Garlic Shrimp Scampi", "Roasted Asparagus", "Lemon Gelato"),
          ("Caprese Stuffed Chicken", "Mixed Green Salad", "Tiramisu"),
          ("Vegetarian Sushi Roll", "Edamame", "Green Tea Ice Cream"),
          ("Pesto Zucchini Noodles", "Cherry Tomatoes", "Almond Biscotti"),
          ("Baked Stuffed Bell Peppers", "Side Garden Salad", "Fresh Berries"),
          ("Honey Mustard Glazed Chicken", "Grilled Vegetables", "Angel Food Cake with Berries"),
          ("Tofu and Broccoli Stir-Fry", "Brown Rice", "Mochi Ice Cream"),
          ("Mediterranean Pasta Salad", "Greek Yogurt with Honey", "Date Balls"),
          ("Zucchini and Tomato Frittata", "Mixed Fruit Salad", "Ricotta Lemon Cake"),
          ("Cauliflower Rice Sushi Roll", "Miso Soup", "Sesame Cookies"),
          ("Greek Quinoa Stuffed Peppers", "Cucumber Salad", "Baklava"),
          ("Lemon Garlic Shrimp Zoodles", "Garlic Breadsticks", "Lemon Sorbet"),
          ("Stuffed Portobello Mushrooms", "Arugula Salad", "Tiramisu"),
          ("Lentil Soup", "Cheese Toast", "Brownie Bites"),
          ("Salmon Salad", "Pita Bread", "Chocolate Pudding"),
          ("Chicken Caesar Salad", "Garlic Breadsticks", "Gelato"),
          ("Turkey Meatballs", "Spaghetti Squash", "Apple Slices w/ Caramel Dip"),
          ("Pork Chops", "Potatoes, Salad", "Cake")]